# Generated by Django 3.2.9 on 2021-11-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='name',
            new_name='title',
        ),
    ]
